[package]
name = "craftping"
version = "0.2.1"
authors = ["kiwiyou <kiwiyou.dev@gmail.com>"]
edition = "2018"
description = "Minecraft Server List Ping Implementation"
license = "MIT"
keywords = ["minecraft", "ping"]
categories = ["network-programming"]
repository = "https://github.com/kiwiyou/craftping"

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]

[features]
default = ["sync"]
sync = []
async-tokio = ["tokio"]

[dependencies]
base64 = { version = "0.13.0" }
serde = { version = "1.0.119", features = ["derive"] }
serde_json = "1.0.61"
tokio = { version = "1.0.2", default-features = false, features = ["net", "io-util"], optional = true }

[dev-dependencies]
tokio = { version = "1.0.2", features = ["macros", "rt"] }
futures = { version = "0.3.12" }
