[package]
name = "craftping"
version = "0.1.0"
authors = ["kiwiyou <kiwiyou.dev@gmail.com>"]
edition = "2018"
description = "Minecraft Server List Ping Implementation"
license = "MIT"
keywords = ["minecraft", "ping"]
categories = ["Network Programming"]
repository = "https://github.com/kiwiyou/craftping"

[features]
default = ["sync"]
sync = []
async-tokio = ["tokio"]

[dependencies]
base64 = { version = "0.13.0" }
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.61"
tokio = { version = "1.0.2", default-features = false, features = ["net", "io-util"], optional = true }

[dev-dependencies]
tokio = { version = "1.0.1", features = ["macros", "rt"] }
futures = { version = "0.3.9" }
